export const DEFAULT_COVER_HALF_POSITION = 70;
export const DEFAULT_COVER_GLIMMER_POSITION = 20;

export const DEFAULT_COVER_CARD_SHOW_STOP_BUTTON = true;
export const DEFAULT_COVER_CARD_SHOW_OPEN_BUTTON = true;
export const DEFAULT_COVER_CARD_SHOW_CLOSE_BUTTON = true;
export const DEFAULT_COVER_CARD_SHOW_HALF_BUTTON = false;
export const DEFAULT_COVER_CARD_SHOW_GLIMMER_BUTTON = false;

export const DEFAULT_COVER_MODAL_SHOW_STOP_BUTTON = true;
export const DEFAULT_COVER_MODAL_SHOW_OPEN_BUTTON = true;
export const DEFAULT_COVER_MODAL_SHOW_CLOSE_BUTTON = true;
export const DEFAULT_COVER_MODAL_SHOW_HALF_BUTTON = true;
export const DEFAULT_COVER_MODAL_SHOW_GLIMMER_BUTTON = true;
export const DEFAULT_COVER_CARD_SHOW_TITLE = true;
export const DEFAULT_MODAL_CARD_SHOW_TITLE = true;
